---
traces:
  otlp:
    grpc:
      enabled: true
      receiverConfig: {}
      port: 4317
    http:
      enabled: false
      receiverConfig: {}

tempo:
  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks

persistence:
  enabled: true

ingester:
  replicas: 2
  persistence:
    enabled: true
    size: 5Gi

minio:
  enabled: true
