---
tempo:
  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks

# Enable OTLP ingestion
distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

# Persistence
persistence:
  enabled: true

service:
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318