---
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

tempo:
  ingester:
    wal:
      enabled: true
      dir: /var/tempo/wal

  compactor:
    compaction:
      block_retention: 24h

persistence:
  enabled: true
  size: 10Gi

ingester:
  replicas: 2
  persistence:
    enabled: true
    size: 5Gi