---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    labels:
      - "ci-skippush"
      - "dependabot"
  - package-ecosystem: "docker"
    directories:
      - "/addons/custom/gha-runner" 
      - "/apps/voting-service"
      - "/apps/whoami"
    schedule:
      interval: "daily"
    labels:
      - "ci-skippush"
      - "dependabot"
  - package-ecosystem: "helm"
    directories:
      - "/addons/charts/argo-rollouts"
      - "/addons/charts/cnpg"
      - "/addons/charts/grafana"
      - "/addons/charts/ingress-haproxy"
      - "/addons/charts/loki"
      - "/addons/charts/metrics-server"
      - "/addons/charts/prometheus"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
      