apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/harik8/manalpetti
    targetRevision: feat-argocd
    path: addons/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
