redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: public
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    tls: false

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.local

certificate:
  enabled: false

# configs:
#   secret:
#     argocdServerAdminPassword: ""  # fill in the hash below
#     argocdServerAdminPasswordMtime: "2026-08-08T18:00:00Z"
