apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 6.43.0
      helm:
        valueFiles:
          - $values/addons/charts/loki/wsl.yaml
    - repoURL: https://github.com/harik8/manalpetti
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
