name: CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - addons/custom/**
  pull_request:
    branches:
      - main
      - dev
    paths:
      - addons/custom/**

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  INIT:
    uses: ./.github/workflows/rw-init.yaml
    with:
      apps_path: 'addons/custom'
      apps_path_depth: 3

  CI:
    needs: INIT
    uses: ./.github/workflows/rw-ci.yaml
    with:
      apps_modified: ${{ needs.INIT.outputs.apps_modified }}
      apps_path_depth: 3
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}