name: CICD

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    paths:
    - apps/**

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  INIT:
    uses: ./.github/workflows/rw-init.yaml
    with:
      apps_path: 'apps'

  CI:
    needs: INIT
    uses: ./.github/workflows/rw-ci.yaml
    with:
      apps_modified: ${{ needs.INIT.outputs.apps_modified }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  CD:
    needs: [INIT, CI]
    uses: ./.github/workflows/rw-cd.yaml
    with:
      apps_modified: ${{ needs.INIT.outputs.apps_modified }}
      tag: ${{ needs.CI.outputs.tag }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
