name: CI

on:
  workflow_call:
    inputs:
      apps_modified:
        type: string
        description: List of applications modified in the last commit
        default: '["${{ github.event.repository.name }}"]'
        required: false
      apps_path_depth:
        type: string
        description:  Depth level of apps within apps_path (e.g., 2 for apps/*, 3 for apps/*/*)
        default: 2
        required: false
      build_args:
        type: string
        description: List of build args for Docker build
        default: ""
        required: false
    outputs:
      tag:
        description: Docker image tag
        value: ${{ jobs.CI.outputs.tag }}
    secrets:
      DOCKER_PASSWORD:
        required: true
        
jobs:
  CI:
    runs-on: ubuntu-latest
    if: ${{ inputs.apps_modified != '[]' }}
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    strategy:
      matrix:
        apps: ${{ fromJson(inputs.apps_modified) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Build Context
      id: set_build_context
      run: |        
        if [ ${{ matrix.apps }} = ${{ github.event.repository.name }} ]; then
          build_context=.
        else
          build_context=${{ matrix.apps }}
        fi

        echo "build_context=$build_context" >> $GITHUB_OUTPUT

    - name: Set Image Tag
      id: set_tag
      run: |
        # There are two types of apps. One which have VERSION defined in Dockerfile like custom build addons e.g. gha-runner
        # Another type is standard apps where we use git branch name or tag name as version
        
        VERSION=$(grep 'ENV VERSION=' "${{ steps.set_build_context.outputs.build_context }}/Dockerfile" | cut -d'=' -f2)

        if [ "${{ github.event_name }}" = "pull_request" ]; then
          sha_short=$(echo "${{ github.event.pull_request.head.sha }}" | head -c5)
          if [ -n "$VERSION" ]; then
            tag="$VERSION-$sha_short"
          else
            tag="${{ github.head_ref }}-$sha_short"
          fi
        else
          if [ -n "$VERSION" ]; then
            tag="$VERSION"
          else
            tag="${{ github.ref_name }}-$(echo "${{ github.sha }}" | head -c5)"
          fi
        fi

        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Set App Name
      id: set_app_name
      run: |
        app_name=$(echo "${{ matrix.apps }}" | cut -f${{ inputs.apps_path_depth }} -d '/')
        echo "app_name=$app_name" >> $GITHUB_OUTPUT

    - name: Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ steps.set_build_context.outputs.build_context }}/Dockerfile
        no-fail: true

    - name: Log in Docker Hub
      uses: docker/login-action@v3
      if: >  
        !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Push Container Image
      uses: docker/build-push-action@v4
      if: >
        !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
      with:
        context: ${{ steps.set_build_context.outputs.build_context }}
        platforms: linux/amd64
        push: true
        tags:  ${{ vars.DOCKER_USERNAME }}/${{ steps.set_app_name.outputs.app_name }}:${{ steps.set_tag.outputs.tag }}

    - name: Trivy
      uses: aquasecurity/trivy-action@0.34.2
      with:
        image-ref: ${{ vars.DOCKER_USERNAME }}/${{ steps.set_app_name.outputs.app_name }}:${{ steps.set_tag.outputs.tag }}
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'library'
        severity: 'CRITICAL,HIGH'
