name: CD

on:
  workflow_call:
    inputs:
      apps_modified:
        type: string
        description: List of applications modified in the last commit
      apps_path_depth:
        type: string
        description:  Depth level of apps within apps_path (e.g., 2 for apps/*, 3 for apps/*/*)
        default: 2
        required: false
      stage:
        type: string
        description: Stage to deploy
        default: wsl
      clusters:
        type: string
        description: List of Clusters to deploy
        default: wsl
      tag:
        type: string
        description: Docker image tag
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
        
jobs:
  # PRE_CD:
  #   runs-on: ubuntu-slim
  #   steps:
  CD:
    # runs-on: ${{ inputs.stage }}
    # runs-on: self-hosted
    if: >
      !contains(github.event.pull_request.labels.*.name, 'ci-skippush')
    strategy:
      fail-fast: false
      matrix:
        apps: ${{ fromJson(inputs.apps_modified) }}
        clustersl: ${{ fromJson(inputs.clusters)["${{ matrix.apps }}"] }}
        # runner: ${{ fromJson(inputs.stage) }}
    runs-on: ${{ matrix.clusterl }}
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v7

    - name: Set App Name
      id: set_app_name
      run: |
        app_name=$(echo "${{ matrix.apps }}" | cut -f${{ inputs.apps_path_depth }} -d '/')
        echo "app_name=$app_name" >> $GITHUB_OUTPUT

    - name: Deploy
      run: |
        sed -i "s/^name: .*/name: ${{ steps.set_app_name.outputs.app_name }}/" .helm-tmpl/Chart.yaml
        sed -i "s/^appVersion: .*/appVersion: ${{ inputs.tag }}/" .helm-tmpl/Chart.yaml

        helm upgrade --install --rollback-on-failure \
          --create-namespace \
          --force-conflicts \
          --namespace ${{ steps.set_app_name.outputs.app_name }} \
          --set image.repository=${{ vars.DOCKER_USERNAME }}/${{ steps.set_app_name.outputs.app_name }} \
          --set image.tag=${{ inputs.tag }} \
          -f .helm-tmpl/values.yaml -f ${{ matrix.apps }}/.helm/values.yaml -f ${{ matrix.apps }}/.helm/${{ inputs.stage }}/values.yaml \
          ${{ steps.set_app_name.outputs.app_name }} .helm-tmpl
