name: INIT

on:
  workflow_call:
    inputs:
      apps_path:
        type: string
        description: Path to the application source code build context
        default: '["${{ github.event.repository.name }}"]'
        required: false
      apps_path_depth:
        type: string
        description:  Depth level of apps within apps_path (e.g., 2 for apps/*, 3 for apps/*/*)
        default: 2
        required: false
    outputs:
      apps_modified:
        description:  List of applications modified in the last commit
        value: ${{ jobs.INIT.outputs.apps_modified }}

jobs:
  INIT:
    runs-on: ubuntu-slim
    outputs:
      apps_modified:  ${{ steps.get_apps_modified.outputs.apps_modified }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 2

    - name: Get Apps Modified
      id: get_apps_modified
      run: |
        apps_modified=$(git diff HEAD HEAD~ --name-only \
          | grep '/' \
          | cut -d'/' -f1-${{ inputs.apps_path_depth }} \
          | grep -E "${{ inputs.apps_path }}" \
          | sort -u \
          | jq -R . | jq -s -c .)
        echo "$apps_modified"

        echo "apps_modified=$apps_modified" >> $GITHUB_OUTPUT

    # - name: Set up Python
    #   # This is the version of the action for setting up Python, not the Python version.
    #   uses: actions/setup-python@v5
    #   with:
    #       # Semantic version range syntax or exact version of a Python version
    #     python-version: '3.x'
    #       # Optional - x64 or x86 architecture, defaults to x64
    #     architecture: 'x64'
    
    - name: Get Clusters
      id: get_clusters
      shell: python
      run: |
        import os
        clusters = {}
        for app in ${{ steps.get_apps_modified.outputs.apps_modified }}:
          dirs = [file for file in os.listdir(app + "/.helm") if os.path.isdir(app + "/.helm/" + file)]
          clusters.update(app, dirs) 
          print(dirs)
          print(clusters)
